config/routes.rb
VERSION_NAME_REGEX = /\d+\.\d+(\.\d+)?(-\w+)?/ unless defined? VERSION_NAME_REGEX

Rails.application.routes.draw do
  require "sidekiq/web"
  require "sidekiq/cron/web"

  mount ActionCable.server => "/cable"
  mount Easymon::Engine => "/up"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # get "up" => "rails/health#show", as: :rails_health_check

  root "authentication/sessions#root"
  get "/admin", to: "admin/settings#index", as: :authenticated_admin_root

  authenticate :email_authentication, ->(u) { u.admin? || Rails.env.development? } do
    mount Flipper::UI.app(Flipper), at: "/flipper"
    mount Sidekiq::Web, at: "/sidekiq"
    mount PgHero::Engine, at: "/pghero"
  end

  devise_for :email_authentication,
    path: :email,
    controllers: {
      registrations: "authentication/email/registrations",
      sessions: "authentication/email/sessions",
      confirmations: "authentication/email/confirmations",
      passwords: "authentication/email/passwords"
    },
    class_name: "Accounts::EmailAuthentication"

  scope module: :authentication do
    namespace :sso do
      get "saml/redeem", to: "sessions#saml_redeem"
      get "sign_in", to: "sessions#new", as: :new_sso_session
      post "sign_in", to: "sessions#create", as: :create_sso_session
      get "sign_out", to: "sessions#destroy", as: :destroy_sso_session
    end
  end

  namespace :authentication do
    resources :invite_confirmations, only: %i[new create], controller: "email/invite_confirmations"
  end

  namespace :accounts do
    resources :organizations, only: [:edit] do
      member do
        get :switch
        get :teams
      end

      resources :teams, only: %i[create update destroy]
      resources :invitations, only: %i[create destroy]
      resources :memberships, only: [:destroy]
    end

    resource :user, only: [:edit, :update] do
      member do
        patch :update_user_role
      end
    end
  end

  resources :apps do
    resource :app_config, only: %i[edit update], path: :config do
      resources :app_variants, only: %i[index edit create update destroy]
    end

    member do
      get :all_builds
      post :refresh_external
    end

    resources :trains, only: %i[new create edit update destroy] do
      member do
        get :rules
        patch :activate
        patch :deactivate
      end

      resource :release_index, only: %i[edit update]
      resources :notification_settings, only: %i[index update edit]

      resources :release_platforms, path: :platforms, as: :platforms do
        resources :release_health_rules, path: :rules
        resource :release_platform_configs, only: %i[edit update], path: :submissions, as: :submission_config, controller: "config/release_platforms"
      end

      resources :releases, only: %i[show create destroy index update], shallow: true do
        member do
          get :overview
          get :changeset_tracking
          get :regression_testing
          get :soak
          get :wrap_up_automations
          patch :override_approvals
          post :copy_approvals
        end

        resources :approval_items, only: %i[index create update destroy], shallow: false

        get :edit, to: "release_metadata#index", path: :metadata, as: :metadata_edit
        patch :update, to: "release_metadata#update_all", path: :metadata, as: :metadata_update
        get :index, to: "beta_releases#index", as: :release_candidates, path: :release_candidates
        get :index, to: "store_submissions#index", path: :store_submission, as: :store_submissions
        get :index, to: "store_rollouts#index", path: :rollout, as: :store_rollouts
        get :index, to: "internal_releases#index", as: :internal_builds, path: :internal_builds

        resources :build_queues, only: [], shallow: false do
          member do
            post :apply
          end
        end

        collection do
          get :live_release
          get :ongoing_release
          get :upcoming_release
          get :hotfix_release
        end

        member do
          get :timeline
          post :post_release
          post :finish_release
        end
      end
    end

    resources :integrations, only: %i[index create destroy] do
      collection do
        post :reuse
        get :connect, to: "integrations#connect", as: :connect

        resource :google_play_store, only: [:create],
          controller: "integrations/google_play_store",
          as: :google_play_store_integration

        resource :bitrise, only: [:create],
          controller: "integrations/bitrise",
          as: :bitrise_integration

        resource :bugsnag, only: [:create],
          controller: "integrations/bugsnag",
          as: :bugsnag_integration

        resource :app_store, only: [:create],
          controller: "integrations/app_store",
          as: :appstore_integration

        resource :google_firebase, only: [:create],
          controller: "integrations/google_firebase",
          as: :google_firebase_integration

        resource :crashlytics, only: [:create],
          controller: "integrations/crashlytics",
          as: :crashlytics_integration
      end

      resources :slack, only: [],
        controller: "integrations/slack",
        as: :slack_integration do
        member do
          post :refresh_channels
        end
      end

      resources :google_firebase, only: [],
        controller: "integrations/google_firebase",
        as: :google_firebase_integration do
        member do
          post :refresh_channels
        end
      end
    end

    get "/integrations/build_artifact_channels", to: "integrations#build_artifact_channels"
  end

  resources :release_platform_runs, path: :runs, as: :runs, only: [] do
    member do
      post :pre_prod_internal, to: "internal_releases#create"
      post :pre_prod_beta, to: "beta_releases#create"
    end

    post :production, to: "production_releases#create"

    resources :pre_prod_releases, shallow: true, only: [] do
      member do
        get :changes_since_previous
      end
    end

    resources :production_releases, shallow: true, only: [] do
      member do
        get :changes_since_previous
      end
    end
  end

  resources :store_rollouts, only: [], shallow: false, path: :rollouts do
    member do
      patch :start
      patch :increase
      patch :pause
      patch :resume
      patch :halt
      patch :fully_release
    end
  end

  resources :store_submissions, only: [:update], shallow: false, path: :store_submissions do
    member do
      patch :retry
      patch :trigger
      patch :submit_for_review
      patch :prepare
      patch :cancel
      patch :remove_from_review
      patch :fully_release_previous_rollout
    end
  end

  if Rails.env.development?
    patch "/store_submissions/:id/mock_reject", to: "store_submissions#mock_reject_for_app_store", as: :mock_reject_for_app_store
    patch "/store_submissions/:id/mock_approve", to: "store_submissions#mock_approve_for_app_store", as: :mock_approve_for_app_store
  end

  resources :workflow_runs, only: [] do
    member do
      patch :retry
      patch :trigger
      patch :fetch_status
    end
  end

  namespace :admin do
    resource :settings, only: [:index]
  end

  namespace :api, defaults: {format: "json"} do
    namespace :v1, path: "v1" do
      get "ping", to: "pings#show"
      get "releases/*release_id", to: "releases#show"
      get "apps/*app_id", to: "apps#show"
      patch "apps/:app_id/builds/:version_name/:version_code/external_metadata",
        to: "builds#external_metadata",
        constraints: {version_name: VERSION_NAME_REGEX}
    end
  end

  scope :github do
    get :callback, controller: "integration_listeners/github", as: :github_callback
    post "/events/:train_id", to: "integration_listeners/github#events", as: :github_events
  end

  scope :gitlab do
    get :callback, controller: "integration_listeners/gitlab", as: :gitlab_callback
    post "/events/:train_id", to: "integration_listeners/gitlab#events", as: :gitlab_events
  end

  scope :bitbucket do
    get :callback, controller: "integration_listeners/bitbucket", as: :bitbucket_callback
    post "/events/:train_id", to: "integration_listeners/bitbucket#events", as: :bitbucket_events
  end

  scope :slack do
    get :callback, controller: "integration_listeners/slack", as: :slack_callback
  end

  scope :jira do
    get :callback, controller: "integration_listeners/jira", as: :jira_callback
    post :callback, controller: "integration_listeners/jira", as: :resend_jira_callback
    get :select_organization, to: "integration_listeners/jira#select_organization", as: :jira_select_organization
  end

  get "/rails/active_storage/blobs/redirect/:signed_id/*filename",
    to: "authorized_blob_redirect#show", as: "blob_redirect"
  match "/", via: %i[post put patch delete], to: "application#raise_not_found", format: false
  match "*unmatched_route", via: :all, to: "application#raise_not_found", format: false,
    constraints: lambda { |req| req.path.exclude? "rails/active_storage" }
end

app/views/apps/_all_builds_search_results.html.erb
<div class="col-span-1 my-4">
    <%= render FilterButtonComponent.new(
    name: "Completed",
    on: filters.dig(:release_status, :is_on),
    path: all_builds_app_path(app),
    method: :get,
    filter_params: get_query_filter(:release_status),
    query_params: all_builds_params) %>
</div>

<% if builds.present? %>
    <%= render AllBuildsTableComponent.new(
    builds: builds,
    paginator: pagy,
    query_params: all_builds_params) %>
    <footer>
    <div class="text-sm text-slate-400">† All timestamps shown are in the timezone configured for the app.</div>
    </footer>
<% else %>
    <%= render EmptyStateComponent.new(
    title: "No builds found",
    text: "Try a different search term or filter, or create a new release to generate builds.",
    banner_image: "drill.svg",
    type: :subdued) %>
<% end %>

app/views/apps/_all_releases_search_results.html.erb
  <div class="col-span-1 my-4">
    <%= render FilterButtonComponent.new(
      name: "Completed",
      on: filters.dig(:release_status, :is_on),
      path: search_app_path(app),
      method: :get,
      filter_params: get_query_filter(:release_status),
      query_params: all_releases_params) %>
  </div>

  <% if releases.present? %>
    <%= render AllReleasesTableComponent.new(
      releases: releases,
      paginator: pagy,
      query_params: all_releases_params) %>
    <footer>
      <div class="text-sm text-slate-400">† All timestamps shown are in the timezone configured for the app.</div>
    </footer>
  <% else %>
    <%= render EmptyStateComponent.new(
      title: "No releases found",
      text: "Try a different search term or filter.",
      banner_image: "drill.svg",
      type: :subdued) %>
  <% end %>

app/views/apps/_edit_form.html.erb
<%= render FormComponent.new(model: [@app], url: app_path(@app), method: :patch) do |f| %>
  <% f.with_section(heading: "Basics") do |section| %>
    <div><%= section.F.labeled_text_field :name, "Name", required: true %></div>
    <div><%= section.F.labeled_textarea :description, "Description" %></div>
  <% end %>

  <% f.with_section(heading: "Build Settings") do |section| %>
    <% section.with_description do %>
      <div>
        If you're going to deploy to the App Store or Play Store, the <strong>bundle identifier</strong> must match
        the identifier in the store listing.
      </div>
      <div class="mt-4">
        The <strong>build number</strong> must be the same or higher than the build number of the last build you
        deployed to the store.
      </div>
    <% end %>

    <div><%= section.F.labeled_text_field :bundle_identifier, "Bundle Identifier", required: true %></div>

    <div data-controller="domain--build-number-help"
         data-domain--build-number-help-number-current-value="<%= @app.build_number.presence %>">
      <%= section.F.labeled_number_field :build_number, "Build Number", data: { domain__build_number_help_target: "input",
                                                                                action: "domain--build-number-help#increment" } %>
      <div class="text-sm mt-1">
        <span data-domain--build-number-help-target="helpTextTitle"></span>&nbsp;
        <span class="font-mono" data-domain--build-number-help-target="helpTextVal"></span>
      </div>
    </div>
  <% end %>

  <% f.with_action do %>
    <% f.F.authz_submit "Update", "archive.svg" %>
  <% end %>
<% end %>

app/views/apps/_form.html.erb
<%= render FormComponent.new(model: [app], free_form: true) do |form| %>
  <div class="grid gap-4 mb-4 sm:grid-cols-2">
    <div><%= form.F.labeled_text_field :name, "Name" %></div>
    <div><%= form.F.labeled_text_field :bundle_identifier, "Bundle Identifier" %></div>

    <div class="sm:col-span-2"
         data-controller="domain--build-number-help"
         data-domain--build-number-help-number-current-value="">

      <%= form.F.labeled_number_field :build_number,
                                    "Build Number",
                                    { data: { domain__build_number_help_target: "input",
                                              action: "domain--build-number-help#increment" } } %>
      <div class="text-sm my-1 dark:text-main-200">
        <p>
          <span data-domain--build-number-help-target="helpTextTitle"></span>&nbsp;
          <span class="font-semibold" data-domain--build-number-help-target="helpTextVal"></span>
        </p>

        <p class="pt-1">
          This number
          <strong>must be</strong> the same or higher than the build number of the last build you
          deployed to the store.
          If you make a mistake, you can edit this later.
        </p>
      </div>
    </div>

    <div><%= form.F.labeled_select :platform, "Mobile Platform", options_for_select(App.allowed_platforms, "Android") %></div>
    <div><%= form.F.labeled_tz_select :timezone, "Timezone", default_timezones, { model: ActiveSupport::TimeZone } %></div>
    <div class="sm:col-span-2"><%= form.F.labeled_textarea :description, "Description" %></div>
  </div>

  <% form.with_action do %>
    <%= form.F.authz_submit "Add an app", "plus.svg" %>
  <% end %>
<% end %>

app/views/apps/_setup_progress.html.erb
<% is_app_config_visible = setup_instructions[:app_config][:visible] %>
<% is_app_config_completed = setup_instructions[:app_config][:completed] %>

<div class="flex flex-col gap-4">
  <%= render SectionComponent.new(title: "Complete your app setup 📲", style: :titled) do %>
    <ol class="flex w-full gap-x-1">
      <% is_app_completed = setup_instructions[:app][:completed] %>
      <li class="relative w-8/12 sm:mb-0">
        <div class="flex items-center">
          <div class="flex z-10 justify-center items-center w-10 h-10 <%= setup_instruction_color(is_app_completed) %> rounded-full ring-0 ring-white sm:ring-8 shrink-0">
            <% if is_app_completed %>
              <%= render IconComponent.new("progress_check.svg", size: :xl_3, classes: "fill-current text-white") %>
            <% end %>
          </div>
        </div>
        <div class="mt-3 sm:pr-10">
          <h3 class="text-lg font-semibold text-main-900">Add an App</h3>
          <p class="text-base font-normal text-secondary">This is complete!</p>
        </div>
      </li>

      <% is_version_control_completed = setup_instructions[:version_control][:completed] %>
      <li class="relative w-full sm:mb-0">
        <div class="flex items-center">
          <div class="flex z-10 justify-center items-center w-10 h-10 <%= setup_instruction_color(is_version_control_completed) %> rounded-full ring-0 ring-white sm:ring-8 shrink-0">
            <% if is_version_control_completed %>
              <%= render IconComponent.new("progress_check.svg", size: :xl_3, classes: "fill-current text-white") %>
            <% end %>
          </div>
        </div>
        <div class="mt-3 sm:pr-10">
          <h3 class="text-lg font-semibold text-main-900">Version Control (VCS) Integration</h3>
          <p class="text-base font-normal text-secondary">
            <% if is_version_control_completed %>
              This is complete!
            <% else %>
              <%= link_to "Configure", app_integrations_path(@app, anchor: "version_control"), class: "underline" %>&nbsp;where
              your code lives.
            <% end %>
          </p>
        </div>
      </li>

      <% is_ci_cd_completed = setup_instructions[:ci_cd][:completed] %>
      <li class="relative w-full sm:mb-0">
        <div class="flex items-center">
          <div class="flex z-10 justify-center items-center w-10 h-10 <%= setup_instruction_color(is_ci_cd_completed) %> rounded-full ring-0 ring-white sm:ring-8 shrink-0">
            <% if is_ci_cd_completed %>
              <%= render IconComponent.new("progress_check.svg", size: :xl_3, classes: "fill-current text-white") %>
            <% end %>
          </div>
        </div>
        <div class="mt-3 sm:pr-10">
          <h3 class="text-lg font-semibold text-main-900">CI/CD Integration</h3>
          <p class="text-base font-normal text-secondary">
            <% if is_ci_cd_completed %>
              This is complete!
            <% else %>
              <%= link_to "Configure", app_integrations_path(@app, anchor: "ci_cd"), class: "underline" %>&nbsp;your
              CI/CD
              provider.
            <% end %>
          </p>
        </div>
      </li>

      <% is_build_channel_completed = setup_instructions[:build_channel][:completed] %>
      <li class="relative w-full sm:mb-0">
        <div class="flex items-center">
          <div class="flex z-10 justify-center items-center w-10 h-10 <%= setup_instruction_color(is_build_channel_completed) %> rounded-full ring-0 ring-white sm:ring-8 shrink-0">
            <% if is_build_channel_completed %>
              <%= render IconComponent.new("progress_check.svg", size: :xl_3, classes: "fill-current text-white") %>
            <% end %>
          </div>
        </div>

        <div class="mt-3 sm:pr-10">
          <h3 class="text-lg font-semibold text-main-900">Deployment Integration</h3>
          <p class="text-base font-normal text-secondary">
            <% if is_build_channel_completed %>
              This is complete!
            <% else %>
              <%= link_to "Configure", app_integrations_path(@app, anchor: "build_channel"), class: "underline" %>&nbsp;one
              or
              more deployment providers for the platform(s).
            <% end %>
          </p>
        </div>
      </li>

      <li class="relative w-full sm:mb-0 <%= "opacity-30" unless is_app_config_visible %>">
        <div class="flex items-center">
          <div class="flex z-10 justify-center items-center w-10 h-10 <%= setup_instruction_color(is_app_config_completed) %> rounded-full ring-0 ring-white sm:ring-8 shrink-0"></div>
        </div>

        <div class="mt-3 sm:pr-2">
          <h3 class="text-lg font-semibold text-main-900">Update Configuration</h3>
          <p class="text-base font-normal text-secondary">
            <% if is_app_config_visible %>
              Finish configuring all your integrations.
            <% else %>
              Finish setting up your integrations first.
            <% end %>
          </p>
        </div>
      </li>
    </ol>
  <% end %>

  <% if is_app_config_visible %>
    <%= render SectionComponent.new(title: "Finish configuring integrations 🔌", style: :titled) do %>
      <ol class="flex w-full gap-x-1">
        <% setup_instructions[:app_config][:integrations].each do |category, statuses| %>
          <% completed = statuses[:completed] %>
          <li class="relative w-full sm:mb-0">
            <div class="flex items-center">
              <div class="flex z-10 justify-center items-center w-10 h-10 <%= setup_instruction_color(completed) %> rounded-full ring-0 ring-white sm:ring-8 shrink-0">
                <% if completed %>
                  <%= render IconComponent.new("progress_check.svg", size: :xl_3, classes: "fill-current text-white") %>
                <% end %>
              </div>
            </div>

            <div class="mt-3 sm:pr-2">
              <h3 class="text-lg font-semibold text-main-900">Configure <%= Integration.human_enum_name(:category, category) %></h3>
              <p class="text-base font-normal text-secondary">
                <% if completed %>
                  You're all set!
                <% else %>
                  <%= link_to "Finish up", app_integrations_path(@app, integration_category: category), class: "underline" %>
                <% end %>
              </p>
            </div>
          </li>
        <% end %>
      </ol>
    <% end %>
  <% end %>
</div>

app/views/apps/all_builds.html.erb
<%= render ContainerComponent.new(title: "All Builds") do |container| %>
  <% container.with_back_button %>
  <% container.with_body do %>
    <%= render SectionComponent.new(style: :titled, title: "Search by version") do %>
      <div class="col-span-1">
        <%= render SearchBarComponent.new(
          path: all_builds_app_path(@app, *@all_builds_params),
          placeholder: "version code or name",
          value: params[:search_pattern],
          turbo_frame: "all_builds") %>
      </div>

      <%= tag.turbo_frame id: "all_builds", target: "_top", data: { turbo_action: "advance" }, class: "col-span-full" do %>
        <div class="col-span-1 my-4">
          <%= render FilterButtonComponent.new(
            name: "Completed",
            on: @filters.dig(:release_status, :is_on),
            path: all_builds_app_path(@app),
            method: :get,
            filter_params: get_query_filter(:release_status),
            query_params: @all_builds_params) %>
        </div>

        <% if @builds.present? %>
          <%= render AllBuildsTableComponent.new(
            builds: @builds,
            paginator: @pagy,
            query_params: @all_builds_params) %>
          <footer>
            <div class="text-sm text-slate-400">† All timestamps shown are in the timezone configured for the app.</div>
          </footer>
        <% else %>
          <%= render EmptyStateComponent.new(
            title: "No builds found",
            text: "Try a different search term or filter, or create a new release to generate builds.",
            banner_image: "drill.svg",
            type: :subdued) %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/apps/edit.html+turbo_frame.erb
<% component = EnhancedTurboFrameComponent.new(dom_id(@app, :edit_app)) %>
<% component.with_loading_indicator %>
<%= render component do %>
  <%= render partial: "edit_form" %>
<% end %>

app/views/apps/edit.html.erb
<%= render TabbedContainerComponent.new(title: @app.name,
                                            turbo_frame: dom_id(@app, :edit_app),
                                            tab_config: @tab_configuration,
                                            error_resource: @app) do |container| %>
  <% container.with_back_button(to: "the app", path: app_path(@app)) %>
  <% container.with_tab do %>
    <%= render partial: "edit_form" %>
  <% end %>
  <% if @app.releases.none? %>
    <% container.with_sub_action do %>
      <%= render ButtonComponent.new(
        scheme: :supporting,
        label: "Remove",
        options: app_path(@app),
        type: :link,
        html_options: { method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the app?" } }) do |b|
        b.with_icon("trash.svg")
      end %>
    <% end %>
  <% end %>
<% end %>

app/views/apps/index.html.erb
<% content_for :sticky_top_message do %>
  <%= render AlertComponent.new(kind: :banner, type: :notice, title: "Need help?", info: { label: "Read docs", link: "https://docs.tramline.app" }) do %>
    Contact us via the chat in the bottom right corner and we'll help you get setup with your release process.
  <% end %>
<% end %>

<%= render ContainerComponent.new(title: "") do |container| %>
  <% if @apps.blank? %>
    <% container.with_empty_state do %>
      <%= render EmptyStateComponent.new(title: "Create an app to get started",
                                             text: "Once you add your app, you can then setup integrations and create your first release.",
                                             banner_image: "art/no_releases.png") do %>
        <%= render ModalComponent.new(title: "Add a new app", dismissable: false) do |modal| %>
          <% modal.with_button(label: "Add a new app", scheme: :default, type: :action, size: :sm, arrow: :none)
                  .with_icon("plus.svg", size: :md) %>
          <% modal.with_body do %>
            <%= render partial: "apps/form", locals: { app: new_app } %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/apps/new_edit.html+turbo_frame.erb
<% component = V2::EnhancedTurboFrameComponent.new(dom_id(@app, :edit_app)) %>
<% component.with_loading_indicator %>
<%= render component do %>
  <%= render partial: "edit_form" %>
<% end %>

app/views/apps/search.html.erb
<%= render ContainerComponent.new(title: "All Releases") do |container| %>
  <% container.with_back_button %>
  <% container.with_body do %>
    <%= render SectionComponent.new(style: :titled, title: "Search by commit/PR") do %>
      <div class="col-span-1">
        <%= render SearchBarComponent.new(
          path: search_app_url(@app, *@all_releases_params),
          placeholder: "Search commit messages",
          value: params[:search_pattern],
          turbo_frame: "search_results") %>
      </div>

      <%= turbo_frame_tag "search_results", data: { turbo_action: "advance" } do %>
        <%= content_tag(:div, id: "all_releases", class: "col-span-full") do %>
          <%= render partial: "apps/all_releases_search_results", locals: { releases: @releases, pagy: @pagy, all_releases_params: @all_releases_params, app: @app, filters: @filters } %>
        <% end %>

        <%= content_tag(:div, id: "all_builds", class: "col-span-full") do %>
          <%= render partial: "apps/all_builds_search_results", locals: { builds: @builds, pagy: @pagy, all_builds_params: @all_builds_params, app: @app, filters: @filters } %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %> 

app/views/apps/show.html.erb
<% content_for :sticky_top_message do %>
  <%= render AlertComponent.new(kind: :banner, type: :notice, title: "Need help?", info: { label: "Read docs", link: "https://docs.tramline.app" }) do %>
    Contact us via the chat in the bottom right corner and we'll help you get setup with your release process.
  <% end %>
<% end %>

<% if @app.ready? && !@app.notifications_set_up? %>
  <% content_for :sticky_top_message do %>
    <%= render AlertComponent.new(kind: :banner, type: :notice, title: "Setup Notifications", info: { label: "Connect", link: app_integrations_path(@app, anchor: "notification")}) do %>
      You haven't yet added the integration for notifications. Set it up to receive timely updates about your release!
    <% end %>
  <% end %>
<% end %>

<%= render ContainerComponent.new(title: "", error_resource: @app) do |container| %>
  <% container.with_body do %>
    <% if @app.ready? %>
      <%= render partial: "shared/draft_mode_notice", locals: { app: @app } %>
      <%= render partial: "trains/setup_progress", locals: {app: @app, train_in_creation: @train_in_creation} %>
    <% else %>
      <%= render partial: "apps/setup_progress", locals: { setup_instructions: @app_setup_instructions } %>
    <% end %>
  <% end %>
<% end %>